[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mysite"
description = "My awesome site"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.1"
dependencies = [
  "fastapi",
  "motor",
]
[tool.setuptools.packages.find]
where = ["src"]